name: Action Practice

on:
  push:
env:
  TZ: Asia/Shanghai

jobs:
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: run
        env:
          KEY: ${{ secrets.KEY }}
        run: |
          python3 -m pip install --upgrade pip
          pip install requests
          python3 ./a.py
      - name: Upload a.txt to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: README.md
          path: ./README.md
      - name: Commit changes
        run: |
          git config --global user.email "2992721672@qq.com"
          git config --global user.name "Ghostasky"
          git add .
          git commit -m "Add"
          git push origin main
